sudo: required
dist: xenial
language: c
cache:
  ccache: true
  directories:
    - $HOME/miniconda3
before_install:
  - bash ./.travis/travis_before_install.sh
install:
  - export PATH=$HOME/miniconda3/bin:$PATH
  - bash install.sh
  - conda install --prefix ./envs/Macrel_env  -y pytest
script:
  - eval "$(conda shell.bash hook)"
  - conda activate ./envs/Macrel_env
  - ./run-tests.sh
  - python -m pytest macrel/tests
